# -*- coding: utf-8 -*-
"""Country/continent and QS alias mappings for formation export."""

COUNTRY_ALIASES = {
    "etats-unis": "United States",
    "etats unis": "United States",
    "united states": "United States",
    "royaume-uni": "United Kingdom",
    "royaume uni": "United Kingdom",
    "grande bretagne": "United Kingdom",
    "uk": "United Kingdom",
    "coree du sud": "South Korea",
    "republique tcheque": "Czech Republic",
    "pays-bas": "Netherlands",
    "suede": "Sweden",
    "suisse": "Switzerland",
    "singapour": "Singapore",
    "finlande": "Finland",
    "norvege": "Norway",
    "slovaquie": "Slovakia",
    "turquie": "Turkey",
    "taiwan": "Taiwan",
    "vietnam": "Vietnam",
    "viet nam": "Vietnam",
    "liban": "Lebanon",
    "lebanon": "Lebanon",
    "maroc": "Morocco",
    "morocco": "Morocco",
    "perou": "Peru",
    "peru": "Peru",
    "indonesie": "Indonesia",
    "indonesia": "Indonesia",
    "iran": "Iran",
    "estonie": "Estonia",
    "estonia": "Estonia",
    "danemark": "Denmark",
    "denmark": "Denmark",
    "chili": "Chile",
    "chile": "Chile",
    "tunisie": "Tunisia",
    "tunisia": "Tunisia",
    "bresil": "Brazil",
    "canada": "Canada",
    "chine": "China",
    "colombie": "Colombia",
    "croatie": "Croatia",
    "espagne": "Spain",
    "grece": "Greece",
    "inde": "India",
    "italie": "Italy",
    "japon": "Japan",
    "russie": "Russia",
    "pologne": "Poland",
    "portugal": "Portugal",
    "roumanie": "Romania",
    "argentine": "Argentina",
    "australie": "Australia",
    "autriche": "Austria",
    "belgique": "Belgium",
    "mexique": "Mexico",
    "uruguay": "Uruguay",
    "allemagne": "Germany",
    "irlande": "Ireland",
}

CODE_COUNTRY = {
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BE": "Belgium",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CN": "China",
    "CO": "Colombia",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "ES": "Spain",
    "FI": "Finland",
    "FN": "Finland",
    "GB": "United Kingdom",
    "GR": "Greece",
    "HR": "Croatia",
    "IN": "India",
    "IT": "Italy",
    "JP": "Japan",
    "KR": "South Korea",
    "MX": "Mexico",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RU": "Russia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SK": "Slovakia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "UR": "Uruguay",
    "US": "United States",
    "UY": "Uruguay",
    "VT": "Vietnam",
}

CONTINENT_BY_COUNTRY = {
    "Argentina": "South America",
    "Australia": "Oceania",
    "Austria": "Europe",
    "Belgium": "Europe",
    "Brazil": "South America",
    "Canada": "North America",
    "China": "Asia",
    "Colombia": "South America",
    "Croatia": "Europe",
    "Czech Republic": "Europe",
    "Finland": "Europe",
    "Germany": "Europe",
    "Greece": "Europe",
    "India": "Asia",
    "Ireland": "Europe",
    "Italy": "Europe",
    "Lebanon": "Asia",
    "Morocco": "Africa",
    "Japan": "Asia",
    "Peru": "South America",
    "Indonesia": "Asia",
    "Mexico": "North America",
    "Iran": "Asia",
    "Netherlands": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Portugal": "Europe",
    "Romania": "Europe",
    "Russia": "Europe",
    "Estonia": "Europe",
    "Denmark": "Europe",
    "Chile": "South America",
    "Singapore": "Asia",
    "Slovakia": "Europe",
    "South Korea": "Asia",
    "Spain": "Europe",
    "Sweden": "Europe",
    "Switzerland": "Europe",
    "Tunisia": "Africa",
    "Taiwan": "Asia",
    "Turkey": "Asia",
    "United Kingdom": "Europe",
    "United States": "North America",
    "Uruguay": "South America",
    "Vietnam": "Asia",
}

# Common abbreviations -> QS official names
QS_ALIAS = {
    "nus": "National University of Singapore (NUS)",
    "kth": "KTH Royal Institute of Technology",
    "tum": "Technical University of Munich",
    "ucl": "UCL",
    "nyu": "New York University (NYU)",
    "polito": "Politecnico di Torino",
    "epm": "Polytechnique Montreal",
    "sutd": "Singapore University of Technology and Design (SUTD)",
    "uc berkeley": "University of California, Berkeley (UCB)",
    "ucb": "University of California, Berkeley (UCB)",
    "lmu": "Ludwig-Maximilians-Universitat Munchen",
    "tu delft": "Delft University of Technology",
    "tudelft": "Delft University of Technology",
    "st andrews": "University of St Andrews",
    "seoul national": "Seoul National University",
    "kaist": "KAIST - Korea Advanced Institute of Science & Technology",
    "eth": "ETH Zurich",
    "epfl": "Ecole Polytechnique Federale de Lausanne (EPFL)",
    "hec montreal": "HEC Montreal",
    "esade": "ESADE Business School",
    "essec": "ESSEC Business School",
    "imperial college": "Imperial College London",
    "ecole polytechnique de montreal": "Polytechnique Montreal",
    "universite de sydney": "University of Sydney",
    "universite de buenos aires": "Universidad de Buenos Aires (UBA)",
    "universidad de buenos aires": "Universidad de Buenos Aires (UBA)",
    "universite technologique de darmstadt": "Technical University of Darmstadt",
    "universite technologique de vienne": "Technische Universitat Wien",
    "universite des sciences et des technologies de taiwan": (
        "National Taiwan University of Science and Technology (Taiwan Tech)"
    ),
    "korea advanced institute of science and technology": (
        "KAIST - Korea Advanced Institute of Science & Technology"
    ),
    "universidad de los andes": "Universidad de los Andes",
    "universite de los andes": "Universidad de los Andes",
    "universidad nacional de colombia": "Universidad Nacional de Colombia",
    "universite nationale de colombie": "Universidad Nacional de Colombia",
    "universidad de zaragoza": "Universidad de Zaragoza",
    "universite de zaragoza": "Universidad de Zaragoza",
    "universidad de zagreb": "University of Zagreb",
    "universite de zagreb": "University of Zagreb",
    "universidad de guadalajara": "Universidad de Guadalajara",
    "universite de guadalajara": "Universidad de Guadalajara",
    "universidade federal do rio de janeiro": "Universidade Federal do Rio de Janeiro",
    "universite federale de rio de janeiro": "Universidade Federal do Rio de Janeiro",
    "pontificia universidade catolica": "Pontificia Universidade Catolica do Rio de Janeiro (PUC-Rio)",
    "pontificia universidad catolica": "Pontificia Universidad Catolica de Chile (UC)",
    "technische universitat wien": "Technische Universitat Wien",
    "tu wien": "Technische Universitat Wien",
    "tuwien": "Technische Universitat Wien",
    "polimi": "Politecnico di Milano",
    "tec de monterrey": "Tecnologico de Monterrey",
    "naist": "Nara Institute of Science and Technology (NAIST)",
    "bogazici": "Bogazici University",
    "shanghai jiaotong": "Shanghai Jiao Tong University",
    "rwth aachen": "RWTH Aachen University",
    "universitat politecnica de catalunya": "Universitat Politecnica de Catalunya",
    "universite polytechnique de valencia": "Universitat Politecnica de Valencia",
    "universidad politecnica de valencia": "Universitat Politecnica de Valencia",
    "universite de technologie de varsovie": "Warsaw University of Technology",
    "warsaw university of technology": "Warsaw University of Technology",
    "la sapienza": "Sapienza University of Rome",
    "sapienza": "Sapienza University of Rome",
    "agh university of science": "AGH University of Science and Technology",
    "agh university of science and technology": "AGH University of Science and Technology",
    "instituto superior tecnico": "University of Lisbon",
    "polytechnique de montreal": "Polytechnique Montreal",
    "ecole polytechnique de montreal": "Polytechnique Montreal",
    "instituto tecnologico de aeronautica": "Instituto Tecnologico de Aeronautica (ITA)",
    "universidade federal do espirito santo": "Universidade Federal do Espirito Santo (UFES)",
    "universidad escuela de ingenieria de antioquia": "Universidad EIA",
    "universite polytechnique de bucarest": "University POLITEHNICA of Bucharest",
    "universite de tohoku": "Tohoku University",
    "tohoku university": "Tohoku University",
    "jonkoping university": "Jonkoping University",
    "master of engineering in industrial engineering operations research": "University of California, Berkeley (UCB)",
    "college of computing": "Georgia Institute of Technology",
    "trinity college dublin": "Trinity College Dublin, The University of Dublin",
    "universite de delft": "Delft University of Technology",
    "universite de saint gall": "University of St.Gallen (HSG)",
    "mit": "Massachusetts Institute of Technology (MIT)",
    "mcgill": "McGill University",
    "uc los angeles": "University of California, Los Angeles (UCLA)",
}
